services:
  web:
    build: .
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: lazordy_db
      POSTGRES_USER: lazordy_user
      POSTGRES_PASSWORD: lazordy22lazordy+l

  #ngrok:
   # image: ngrok/ngrok:latest
   # restart: unless-stopped
   # depends_on:
    #  - web
   # command: http web:8000
    #environment:
     # NGROK_AUTHTOKEN: 2zQ3XvfhLBaYHBs9lGiQzFsFTQJ_6GgjWG1zsYz9xkF547Cih

  #ngrok-updater:
   # build:
    #  context: .
    #command: python scripts/update_ngrok_env.py
    #volumes:
     # - .:/app
    #depends_on:
     # - ngrok

volumes:
  postgres_data:
